config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "homes#top"


  # 一般的な検索用のルート
  get "search" => "searches#search"

  # ユーザー関連のルート
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get 'search', as: :search
    end
  end

  # ポスト関連のルート
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments # コメントリソースをpostsリソース内にネスト
    resources :maps # Postに関連するMapエンドポイントをネスト

    collection do
      get 'search', as: :search
    end
  end

  # マップ関連のルート
  resources :maps, only: [:index, :show] do
    collection do
      get 'search', as: :search
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :search_results, only: [:index]

  resources :reports, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  scope :deleted, -> { where.not(deleted_at: nil) }
  scope :alive, -> { where(deleted_at: nil) }

  def soft_delete
    update(deleted_at: Time.current)
  end


  def self.ransackable_attributes(auth_object = nil)
  %w[name]
  end


  # アソシエーションもろもろ

   has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: "followee_id", dependent: :destroy

  has_many :following, through: :active_follows, source: :followee
  has_many :followers, through: :passive_follows, source: :follower

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 通報機能
  has_many :reports, class_name: 'Report', foreign_key: 'reported_post_id', dependent: :destroy
  # レベル、エリア、ポイントのカスタム属性

  # レベルだめかもしれない。間に合わない。
  # attr_accessor :level, :area

  # バリデーションを追加
  # validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # validates :area, presence: false
  # validates :points, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

  has_one_attached :profile_image

  #ゲストユーザー
 def self.guest
  timestamp = Time.now.to_i

  find_or_create_by!(email: "guest_#{timestamp}@example.com") do |user|
    user.name = "@guest_#{timestamp}"
    user.password = SecureRandom.urlsafe_base64
  end
end



  def increase_points(amount)
    update(points: points + amount)
  end

  def decrease_points(amount)
    update(points: points - amount)
  end

  # カスタム属性へのアクセス方法を定義
  # def level
    # self[:level] || 0 # レベルが nil の場合はデフォルト値 0 を返す
  # end

  # def area
    # self[:area] || "" # エリアが nil の場合は空文字列を返す
  # end

  # ユーザーのレベル、エリア、ポイントを設定
  # def set_user_attributes(level, area, points)
    # update(level: level, area: area, points: points)
  # end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def add_at_to_name
    self.name.prepend("@") unless name&.start_with?("@")
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def new
    @posts = Post.all
    @post = Post.new
    @maps = Map.includes(:post_maps => :post).all
    super
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, only: [:edit, :update]

def show
  @user = User.find(params[:id])
end

def search
  @q = User.ransack(params[:q])
  @users = @q.result(distinct: true)
end

  def following
    @user = User.find(params[:id])
    @following = @user.following
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
  end

  def user_params
      params.require(:user).permit(:name, :profile, :snap)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<% if user_signed_in? %>
  <div class="bg-light p-3 border rounded">
    <div class="text-center">
      <% if current_user.profile_image.present? %>
        <%= link_to image_tag(current_user.profile_image, class: "rounded-circle shadow mb-3", style: "width: 150px; height: 150px;"), user_path(current_user) %>
      <% else %>
        <%= link_to image_tag('defaultuser.png', class: "rounded-circle shadow mb-3", style: "width: 150px; height: 150px;"), user_path(current_user) %>
      <% end %>
      <h2 class="text-dark"><%= current_user.name %></h2>
      <p class="text-secondary">フォロー: <%= current_user.following.count %> | フォロワー: <%= current_user.followers.count %></p>
      <div>
        <%= link_to 'プロフィールを編集', edit_user_registration_path, class: "btn btn-outline-dark btn-sm" %>
      </div>
    </div>
  </div>
<% else %>
  <div class="bg-light p-3 border rounded text-center">
    <p class="mb-3">ログインしていません</p>
    <%= link_to 'ログイン', new_user_session_path, class: "btn btn-outline-dark btn-sm" %>
    <%= link_to '新規登録', new_user_registration_path, class: "btn btn-outline-dark btn-sm ml-2" %>
  </div>
<% end %>

app/views/users/_user_search.html.erb
<% if @results_user.present? %>
  <h3>User Search Results</h3>
  <ul>
    <% @results_user.each do |user| %>
      <li><%= link_to user.user_name, user_path(user) %></li>
    <% end %>
  </ul>
<% else %>
  <h3>No user found</h3>
<% end %>

app/views/users/followers.html.erb
<div class="container mt-5">
  <h2>Followers</h2>
  <ul class="list-group">
    <% @followers.each do |user| %>
      <li class="list-group-item">
        <%= image_tag user.profile_image.present? ? user.profile_image : 'defaultuser.png', class: "rounded-circle", style: "width: 50px; height: 50px;" %>
        <%= link_to user.name, user_path(user) %>
        <span>フォロー: <%= user.following.count %> | フォロワー: <%= user.followers.count %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/following.html.erb
<div class="content-section" id="follow">
  <h2>Following Users</h2>
  <% if user_signed_in? %>
    <ul class="list-group">
      <% if @following.any? %>
        <% @following.each do |user| %>
          <li class="list-group-item d-flex align-items-center">
            <% if user.profile_image.present? %>
              <%= image_tag user.profile_image.url, size: "50x50", class: "rounded-circle me-3" %>
            <% else %>
              <%= image_tag 'defaultuser.png', size: "50x50", class: "rounded-circle me-3" %>
            <% end %>
            <div class="d-flex flex-column">
              <%= link_to user.name, user_path(user), class: "font-weight-bold text-decoration-none text-dark" %>
              <small class="text-muted">
                Following: <%= user.following.count %> | Followers: <%= user.followers.count %>
              </small>
            </div>
          </li>
        <% end %>
      <% else %>
        <p>フォローしているユーザーはいません</p>
      <% end %>
    </ul>
  <% else %>
    <p>You need to sign in to see the people you are following.</p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-3 bg-light p-3 border-right">
      <div class="text-center">
        <% if @user.profile_image.present? %>
          <%= image_tag @user.profile_image, class: "rounded-circle shadow mb-3", style: "width: 150px; height: 150px;" %>
        <% else %>
          <%= image_tag 'defaultuser.png', class: "rounded-circle shadow mb-3", style: "width: 150px; height: 150px;" %>
        <% end %>
        <h2 class="text-dark"><%= @user.name %></h2>
        <p class="text-secondary">
          フォロー: <%= link_to @user.following.count, following_user_path(@user) %> |
          フォロワー: <%= link_to @user.followers.count, followers_user_path(@user) %>
        </p>
        <% unless current_user.nil? || current_user == @user %>
          <div id="follow_form" class="mb-2">
            <% if current_user.following?(@user) %>
              <%= render 'follows/unfollow' %>
            <% else %>
              <%= render 'follows/follow' %>
            <% end %>
          </div>
          <div>
            <%= link_to '通報する', new_report_path(reporter_id: current_user.id, reported_id: @user.id), class: "btn btn-outline-dark" %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- Main content area -->
    <div class="col-md-9 bg-white p-3">
      <div class="row">
        <% @user.posts.each do |post| %>
          <div class="col-md-3 mb-4">
            <div class="card" style="height: 100%;">
              <%= link_to post_path(post) do %>
                <%= image_tag post.snap.url, class: "card-img-top img-fluid rounded shadow", alt: post.body %>
              <% end %>
              <div class="card-body">
                <div class="text-center">
                  <small>
                    Likes: <%= post.likes.count %> |
                    Comments: <%= post.comments.count %> |
                    Spot: <%= post.maps.first&.spot_name || 'N/A' %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>