config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "homes#top"


  # 一般的な検索用のルート
  get "search" => "searches#search"

  # ユーザー関連のルート
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get 'search', as: :search
    end
  end

  # ポスト関連のルート
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments # コメントリソースをpostsリソース内にネスト
    resources :maps # Postに関連するMapエンドポイントをネスト

    collection do
      get 'search', as: :search
    end
  end

  # マップ関連のルート
  resources :maps, only: [:index, :show] do
    collection do
      get 'search', as: :search
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :search_results, only: [:index]

  resources :reports, only: [:new, :create]
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:followee_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Follow.find(params[:id]).followee
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<%= form_with(url: follows_path, remote: true) do |f| %>
  <div><%= hidden_field_tag :followee_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/follows/_unfollow.html.erb
<%= form_with(url: follow_path(current_user.active_follows.find_by(followee_id: @user.id)), method: :delete, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary" %>
<% end %>

app/views/follows/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/follows/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");