config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "homes#top"


  # 一般的な検索用のルート
  get "search" => "searches#search"

  # ユーザー関連のルート
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get 'search', as: :search
    end
  end

  # ポスト関連のルート
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments # コメントリソースをpostsリソース内にネスト
    resources :maps # Postに関連するMapエンドポイントをネスト

    collection do
      get 'search', as: :search
    end
  end

  # マップ関連のルート
  resources :maps, only: [:index, :show] do
    collection do
      get 'search', as: :search
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :search_results, only: [:index]

  resources :reports, only: [:new, :create]
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid
  scope :deleted, -> { where.not(deleted_at: nil) }
  scope :alive, -> { where(deleted_at: nil) }

  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  belongs_to :user
  has_many :post_maps, dependent: :destroy
  has_many :maps, through: :post_maps
  has_many :reports, class_name: 'Report', foreign_key: 'reported_post_id'

  validates :body, presence: true
  validates :snap, presence: true

  mount_uploader :snap, PostSnapUploader # CarrierWave

  def liked_by?(user)
  likes.where(user_id: user.id).exists?
  end

  def self.ransackable_attributes(auth_object = nil)
    %w(body) + _ransackers.keys
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authenticate_user!, only: [:edit, :update, :destroy]
 before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments.where(parent_id: nil).includes(:replies) # 主コメントとそのリプライを取得
    @comment = @post.comments.new
  end

  def new
    @post = Post.new
    @post.maps.build
  end

  def create
    @post = current_user.posts.new(post_params)
        # MapのIDがparamsに存在する場合は、そのMapオブジェクトを@postのmapに設定
      if @post.save
         @map = Map.new(map_params)
         @map.post_id = @post.id
         @map.save!
         @post_map = PostMap.new(post_id:@post.id,map_id:@map.id)
         @post_map.save!
         latitude = params[:map][:latitude]
         longitude = params[:map][:longitude]
        # 緯度と経度を関連するMapオブジェクトにも保存する(仮定)
        #@post.maps.create(latitude: params[:post][:latitude], longitude: params[:post][:longitude])
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
  end

  def edit
    @post = Post.find(params[:id])
    @post_map = PostMap.find_by(post_id: @post.id)
    @map = Map.find(@post_map.map_id) if @post_map
  end


  def update
    @post = current_user.posts.find(params[:id])
  if @post.update(post_params)
    @post_map = PostMap.find_by(post_id: @post.id)
    @map = Map.find(@post_map.map_id) if @post_map
    if @map
      @map.update(spot_name: params[:map][:spot_name])
    end
    redirect_to @post, notice: 'Post was successfully updated.'
  else
    render :edit
  end
end


  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: 'Post was successfully destroyed.'
  end

  def search
  @q = Post.ransack(params[:q])
  @posts = @q.result(distinct: true)
  end

  private
   def correct_user
       @post = Post.find(params[:id])
    unless current_user == @post.user
        redirect_to root_path, alert: "Not authorized"
    end
   end

   def post_params
     params.require(:post).permit(:body, :snap, maps_attributes: [:id, :latitude, :longitude, :spot_name, :description, :photo_url, :_destroy])
   end

   def map_params
    params.require(:map).permit(:latitude, :longitude, :spot_name, :description, :photo_url)
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if user_signed_in? %>

<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="alert alert-dark">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :spot_name, class: 'form-label text-dark' %>
    <%= text_field_tag 'map[spot_name]', nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <button type="button" class="btn btn-dark" onclick="getCurrentLocation()">現在位置を使用する</button>
    <!-- btn-darkでモノクロに -->
  </div>

  <!-- 現在座標を保存するための隠しフィールド -->
  <input type="text" name="map[latitude]" id="latitude" readonly>
  <input type="text" name="map[longitude]" id="longitude" readonly>

  <div class="form-group">
    <%= form.label :title, "Title", class: 'form-label text-dark' %>
    <%= form.text_area :body, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :snap, "Image", class: 'form-label text-dark' %>
    <%= form.file_field :snap, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-dark' %>
  </div>
<% end %>
  <% else %>
  <div class="bg-light p-3 border rounded text-center">
    <p class="mb-3">ログインしていません</p>
    <%= link_to 'ログイン', new_user_session_path, class: "btn btn-outline-dark btn-sm" %>
    <%= link_to '新規登録', new_user_registration_path, class: "btn btn-outline-dark btn-sm ml-2" %>
  </div>
<% end %>



<script>

// 現在位置取得

function getCurrentLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition((position) => {
      document.getElementById('latitude').value = position.coords.latitude;
      document.getElementById('longitude').value = position.coords.longitude;
      alert('現在位置を取得しました');
    }, () => {
      alert('位置情報の取得に失敗しました');
    });
  } else {
    alert('このブラウザは位置情報の取得をサポートしていません');
  }
}
</script>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
  <li class="list-group-item">
    <div class="row">
      <div class="col-md-4">
        <%= link_to "javascript:void(0)", onclick: "centerMap(#{post.maps.first.latitude}, #{post.maps.first.longitude})" do %>
          <%= image_tag post.snap.url, alt: post.body, class: "img-fluid" %>
        <% end %>
      </div>
      <div class="col-md-8">
        <strong>
          <%= link_to post.body, post_path(post) %>
        </strong>
        <p>
          <span class="font-weight-bold">Spot:</span> <%= post.maps.first&.spot_name || 'N/A' %><br>
          <span class="font-weight-bold">Posted by:</span> <%= link_to post.user.name, user_path(post.user) %><br>
          <span class="font-weight-bold">Likes:</span> <%= post.likes.count %> | <span class="font-weight-bold">Comments:</span> <%= post.comments.count %>
        </p>
      </div>
    </div>
  </li>
<% end %>

app/views/posts/edit.html.erb
<!-- app/views/posts/edit.html.erb -->

<h1>Edit Post</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- 投稿の画像を表示 -->
  <<% if @post.snap.file.present? %>
  <%= image_tag @post.snap.url, class: 'img-thumbnail', width: '200' %>
<% end %>

  <div class="form-group">
    <%= form.label :spot_name, class: 'form-label text-dark' %>
    <%= text_field_tag 'map[spot_name]', nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body, "Body", class: 'form-label text-dark' %>
    <%= form.text_area :body, class: 'form-control', required: true, value: @post.body %>
  </div>

  <div class="actions">
    <%= form.submit 'Update', class: 'btn btn-dark' %>
  </div>

  <!-- 削除ボタン -->
  <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

<% end %>

app/views/posts/new.html.erb
<h2>新規投稿</h2>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :snap %>
    <%= form.file_field :snap %>
  </div>

  <%= form.fields_for :maps do |map_fields| %>
    <div class="field">
      <%= map_fields.label :latitude %>
      <%= map_fields.text_field :latitude %>
    </div>

    <div class="field">
      <%= map_fields.label :longitude %>
      <%= map_fields.text_field :longitude %>
    </div>

    <div class="field">
      <%= map_fields.label :spot_name %>
      <%= map_fields.text_field :spot_name %>
    </div>

    <div class="field">
      <%= map_fields.label :description %>
      <%= map_fields.text_area :description %>
    </div>

    <div class="field">
      <%= map_fields.label :photo_url %>
      <%= map_fields.text_field :photo_url %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row align-items-center mb-4">
    <!-- ユーザー情報 -->
    <div class="col-md-2">
        <% if @user.profile_image.present? %>
          <%= image_tag @user.profile_image, class: "rounded-circle shadow mb-3", style: "width: 150px; height: 150px;" %>
        <% else %>
          <%= image_tag 'defaultuser.png', class: "rounded-circle shadow mb-3", style: "width: 150px; height: 150px;" %>
        <% end %>
</div>
    <div class="col-md-10">
      <p>
        <%= link_to @post.user.name, user_path(@post.user), class: 'font-weight-bold text-decoration-none' %>
      </p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-12">
      <% if @post.snap.present? %>
        <%= image_tag @post.snap.url, class: 'img-fluid' %>
      <% else %>
        <h1 class="text-center">No Image Available</h1>
      <% end %>
      <p class="mt-3"><%= @post.body %></p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-12">
      <%= render partial: 'likes/like', locals: { post: @post } %>
          <span id="like-count" class="ml-2"><%= @post.likes.count %></span>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-12">
      <%= render partial: 'comments/form', locals: { post: @post } %>
    </div>
  </div>
  <div class="comments-section">
    <div class="row mt-4">
      <div class="col-md-12">
        <% @comments.each do |comment| %>
          <%= render partial: 'comments/comment', locals: { comment: comment, replies: comment.replies, post: @post } %>
        <% end %>
      </div>
    </div>
  </div>

  <!--% if user_signed_in? %>-->
    <!--%= link_to '通報する', new_report_path(reporter_id: current_user.id, user_id: @post.user_id, post_id: @post.id) %>-->
  <!--% end %>-->
  <div class="row mt-4">
    <div class="col-md-12">
      <% if user_signed_in? && current_user == @post.user %>
        <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-secondary me-2' %> |
      <% end %>
      <%= link_to 'Back', root_path , data: {"turbolinks" => false}, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>