config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "homes#top"


  # 一般的な検索用のルート
  get "search" => "searches#search"

  # ユーザー関連のルート
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get 'search', as: :search
    end
  end

  # ポスト関連のルート
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments # コメントリソースをpostsリソース内にネスト
    resources :maps # Postに関連するMapエンドポイントをネスト

    collection do
      get 'search', as: :search
    end
  end

  # マップ関連のルート
  resources :maps, only: [:index, :show] do
    collection do
      get 'search', as: :search
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :search_results, only: [:index]

  resources :reports, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent, class_name: 'Comment', optional: true

  validates :body, presence: true


  def depth
    parent ? parent.depth + 1 : 0
  end


end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id, message: "You can't like a post more than once" }
end

app/models/map.rb
class Map < ApplicationRecord
  mount_uploader :photo_url, PostSnapUploader
  has_many :post_maps, dependent: :destroy
  # Geocoderで緯度経度から住所を取得
  #  geocoded_by :spot_name
   # after_validation :geocode
  #validates :latitude, :longitude, presence: true
  validates :spot_name,  presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w(spot_name) + _ransackers.keys
  end


end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid
  scope :deleted, -> { where.not(deleted_at: nil) }
  scope :alive, -> { where(deleted_at: nil) }

  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  belongs_to :user
  has_many :post_maps, dependent: :destroy
  has_many :maps, through: :post_maps
  has_many :reports, class_name: 'Report', foreign_key: 'reported_post_id'

  validates :body, presence: true
  validates :snap, presence: true

  mount_uploader :snap, PostSnapUploader # CarrierWave

  def liked_by?(user)
  likes.where(user_id: user.id).exists?
  end

  def self.ransackable_attributes(auth_object = nil)
    %w(body) + _ransackers.keys
  end

end

app/models/post_map.rb
class PostMap < ApplicationRecord
  belongs_to :post
  belongs_to :map
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reporter, class_name: 'User', foreign_key: 'reporter_id'
  belongs_to :reported, class_name: 'User', foreign_key: 'reported_id', optional: true
  belongs_to :reported_post, class_name: 'Post', foreign_key: 'reported_post_id', optional: true

  validates :reason, presence: true
  validate :either_reported_or_reported_post_present

  enum status: { waiting: 0, keep: 1, finish: 2 }

  private

  def either_reported_or_reported_post_present
    if reported_id.blank? && reported_post_id.blank?
      errors.add(:base, "報告されたユーザーまたは投稿のいずれかが存在しなければなりません")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  scope :deleted, -> { where.not(deleted_at: nil) }
  scope :alive, -> { where(deleted_at: nil) }

  def soft_delete
    update(deleted_at: Time.current)
  end


  def self.ransackable_attributes(auth_object = nil)
  %w[name]
  end


  # アソシエーションもろもろ

   has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_follows, class_name: "Follow", foreign_key: "followee_id", dependent: :destroy

  has_many :following, through: :active_follows, source: :followee
  has_many :followers, through: :passive_follows, source: :follower

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 通報機能
  has_many :reports, class_name: 'Report', foreign_key: 'reported_post_id', dependent: :destroy
  # レベル、エリア、ポイントのカスタム属性

  # レベルだめかもしれない。間に合わない。
  # attr_accessor :level, :area

  # バリデーションを追加
  # validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # validates :area, presence: false
  # validates :points, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

  has_one_attached :profile_image

  #ゲストユーザー
 def self.guest
  timestamp = Time.now.to_i

  find_or_create_by!(email: "guest_#{timestamp}@example.com") do |user|
    user.name = "@guest_#{timestamp}"
    user.password = SecureRandom.urlsafe_base64
  end
end



  def increase_points(amount)
    update(points: points + amount)
  end

  def decrease_points(amount)
    update(points: points - amount)
  end

  # カスタム属性へのアクセス方法を定義
  # def level
    # self[:level] || 0 # レベルが nil の場合はデフォルト値 0 を返す
  # end

  # def area
    # self[:area] || "" # エリアが nil の場合は空文字列を返す
  # end

  # ユーザーのレベル、エリア、ポイントを設定
  # def set_user_attributes(level, area, points)
    # update(level: level, area: area, points: points)
  # end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def add_at_to_name
    self.name.prepend("@") unless name&.start_with?("@")
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end



end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  def new
    @map = Map.new
  end

  def create
    @map = Map.new(map_params)

    if @map.save
      redirect_to @map, notice: 'Map was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @map.update(map_params)
      redirect_to @map, notice: 'Map was successfully updated.'
    else
      render :edit
    end
  end

  def index
    @maps = Map.all
    @post = Post.new
    @posts = Post.all
  end

def search
  @q = Map.ransack(params[:q])
  @maps = @q.result(distinct: true)
end



  private

  def set_map
    @map = Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:latitude, :longitude, :spot_name, :description, :photo_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_follow_section.html.erb
<div class="content-section d-none" id="follow">
  <h2>Following Users</h2>
  <% if user_signed_in? %>
    <ul class="list-group">
      <% if current_user.following.any? %>
        <% current_user.following.each do |user| %>
           <li class="list-group-item">
            <%= image_tag user.profile_image.url, size: "50x50", class: "rounded-circle me-3" if user.profile_image.present? %>
            <%= link_to user.name, user_path(user), class: "font-weight-bold text-decoration-none text-dark" %>
          </li>
        <% end %>
      <% else %>
        <p>フォローしているユーザーはいません</p>
      <% end %>
    </ul>
  <% else %>
    <p>You need to sign in to see the people you are following.</p>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "Logo", style: "height: 50px; width: auto;" %>
    <% end %>
    <%= render 'layouts/search' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link no-js' do %>
              <i class="fas fa-sign-out-alt"></i>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to users_guest_sign_in_path, method: :post, class: 'nav-link no-js' do %>
              <i class="fas fa-user-secret"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link no-js' do %>
              <i class="fas fa-user-plus"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link no-js' do %>
              <i class="fas fa-sign-in-alt"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_likes_section.html.erb
<div class="content-section d-none" id="likes">
  <h2>Your Likes</h2>
  <% if user_signed_in? %>
    <ul class="list-group">
      <% current_user.liked_posts.each do |post| %>
        <li class="list-group-item">
          <div class="row">
            <div class="col-md-4">
              <%= link_to "javascript:void(0)", onclick: "centerMap(#{post.maps.first.latitude}, #{post.maps.first.longitude})" do %>
                <img src="<%= post.snap.url %>" alt="<%= post.body %>" class="img-fluid">
              <% end %>
            </div>
            <div class="col-md-8">
              <strong>
                <%= link_to post.body, post_path(post) %>
              </strong>
              <p>
                Posted by: <%= link_to post.user.name, user_path(post.user) %><br>
                Likes: <%= post.likes.count %> | Comments: <%= post.comments.count %>
              </p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>You need to sign in to see your liked posts.</p>
  <% end %>
</div>

app/views/layouts/_post_section.html.erb
<div id="post" class="content-section d-none">
 <%= render 'posts/form', post: @post %>
</div>

app/views/layouts/_profile_section.html.erb
<div id="profile" class="content-section d-none">
 <%= render 'users/profile', user: @user %>
</div>

app/views/layouts/_search.html.erb
<div class="container">
  <br/>
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
        <div class="form-group row no-gutters align-items-center">
          <div class="col-auto">
          </div>
          <!-- end of col -->
          <div class="col">
            <%= f.text_field :q, class: "form-control form-control-lg form-control-borderless text-gray", placeholder: "Search..." %>
          </div>
          <!-- end of col -->
          <div class="col-auto">
            <%= f.button type: "submit", class: "btn btn-lg btn-gray" do %>
              <!-- フォントアイコンをボタンに追加 -->
              <i class="fas fa-search"></i>
            <% end %>
          </div>
          <!-- end of col -->
        </div>
      <% end %>
    </div>
    <!-- end of col -->
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<style>
  .nav-link.text-gray {
    color: gray !important;
  }
</style>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 bg-light">
      <ul class="nav flex-row justify-content-center">
        <li class="nav-item">
          <a class="nav-link text-gray" href="#" data-content="profile">
            <i class="fas fa-user"></i> Profile
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-gray" href="#" data-content="spot">
            <i class="fas fa-map-marker-alt"></i> Spot
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-gray" href="#" data-content="post">
            <i class="fas fa-pen"></i> Post
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-gray" href="#" data-content="likes">
            <i class="fas fa-thumbs-up"></i> Likes
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-gray" href="#" data-content="follow">
            <i class="fas fa-users"></i> Follow
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_spot_section.html.erb
<div id="spot" class="content-section d-none">
  <%= render 'posts/list' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WonderSnap</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!--<script src="http://maps.google.com/maps/api/js?key=AIzaSyDUFgWwu57R50ATnJ6zmPeO3Xuphjn620w&language=ja"></script>-->
  <script src="https://kit.fontawesome.com/079d0f24e7.js" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</head>

<body>
  <header>
    <%= render 'layouts/header' %>
  </header>

  <main style="min-height: 55vh;" class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> cake-font">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
</main>



  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</body>
</html>